Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.berkshelf.enabled = true
	config.berkshelf.berksfile_path = "cookbooks/nginx-helloworld/Berksfile"
	config.vm.provision :chef_solo do |chef|
		chef.cookbooks_path = "cookbooks"
		chef.add_recipe "nginx-helloworld"
	end
end
