Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	#config.vm.network "private_network", ip: 192.168.50.4
	config.vm.network "forwarded_port", guest:80, host: 8081
	config.vm.provision "ansible_local" do |ansible|
		#ansible.inventory_path = "wordpress-playbook/hosts"
		ansible.playbook = "wordpress-playbook/playbook.yml"
	end
end

